=== bob-collective/tokenlist/chain.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Chain Registry Schema",
  "type": "object",
  "definitions": {
    "LogoURI": {
      "type": "string",
      "oneOf": [{ "format": "uri-reference" }, { "format": "uri" }]
    }
  },
  "properties": {
    "$schema": {
      "type": "string",
      "oneOf": [{ "format": "uri-reference" }, { "format": "uri" }]
    },
    "bob": {
      "$ref": "#/definitions/LogoURI"
    },
    "bob-sepolia": {
      "$ref": "#/definitions/LogoURI"
    },
    "ethereum": {
      "$ref": "#/definitions/LogoURI"
    },
    "sepolia": {
      "$ref": "#/definitions/LogoURI"
    },
    "bnb-smart-chain": {
      "$ref": "#/definitions/LogoURI"
    },
    "base": {
      "$ref": "#/definitions/LogoURI"
    },
    "op-mainnet": {
      "$ref": "#/definitions/LogoURI"
    },
    "arbitrum-one": {
      "$ref": "#/definitions/LogoURI"
    },
    "polygon": {
      "$ref": "#/definitions/LogoURI"
    },
    "avalanche": {
      "$ref": "#/definitions/LogoURI"
    },
    "unichain": {
      "$ref": "#/definitions/LogoURI"
    },
    "sonic": {
      "$ref": "#/definitions/LogoURI"
    },
    "sei-network": {
      "$ref": "#/definitions/LogoURI"
    },
    "soneium-mainnet": {
      "$ref": "#/definitions/LogoURI"
    },
    "berachain": {
      "$ref": "#/definitions/LogoURI"
    },
    "telos": {
      "$ref": "#/definitions/LogoURI"
    },
    "hyper-evm": {
      "$ref": "#/definitions/LogoURI"
    },
    "plasma": {
      "$ref": "#/definitions/LogoURI"
    },
    "tron": {
      "$ref": "#/definitions/LogoURI"
    },
    "solana": {
      "$ref": "#/definitions/LogoURI"
    },
    "bitcoin": {
      "$ref": "#/definitions/LogoURI"
    },
    "signet": {
      "$ref": "#/definitions/LogoURI"
    },
    "robinhood-chain": {
      "$ref": "#/definitions/LogoURI"
    }
  },
  "additionalProperties": false
}

=== bob-collective/tokenlist/data/chains/chains.json
{
  "$schema": "../../chain.schema.json",
  "bob": "bob.svg",
  "bob-sepolia": "bob.svg",
  "ethereum": "ethereum.svg",
  "sepolia": "ethereum.svg",
  "bnb-smart-chain": "bsc.svg",
  "base": "base.svg",
  "op-mainnet": "optimism.svg",
  "arbitrum-one": "arbitrum.svg",
  "polygon": "polygon.svg",
  "avalanche": "avalanche.svg",
  "unichain": "unichain.svg",
  "sonic": "sonic.svg",
  "sei-network": "sei.svg",
  "soneium-mainnet": "soneium.svg",
  "berachain": "berachain.svg",
  "telos": "telos.svg",
  "plasma": "plasma.svg",
  "hyper-evm": "hyperevm.svg",
  "tron": "tron.svg",
  "solana": "solana.svg",
  "bitcoin": "bitcoin.svg",
  "signet": "signet.svg",
  "robinhood-chain": "robinhood.svg"
}
